#support multiple orgs eventually
org: Example2
org_desc:  Mining Rupees Daily
users:
  - username: link
    email: link@veloe.com.br
    first_name: Link
    is_superuser: yes
    last_name: Smith
    password: teste

  - username: gdorf
    email: gannon@veloe.com.br
    first_name: Gannon
    is_superuser: false
    last_name: Dorf
    password: teste

  - username: zelda
    email: zelda@veloe.com.br
    first_name: Zelda
    is_superuser: false
    last_name: Smith
    password: teste

  - username: epona
    email: epona@veloe.com.br
    first_name: Epona
    is_superuser: false
    last_name: Horse
    password: teste     

  - username: demise
    email: demise@veloe.com.br
    first_name: De
    is_superuser: false
    last_name: Mise
    password: teste     

teams:
  - name: Ops2
    description: The Ops Team
    users:
    - link
  - name: QA2
    description: The QA Team
    users:
    - gdorf
  - name: Dev2
    description: The Dev Team
    users:
    - zelda

credentials:
  - name: EC2 SSH
    description:  Used for EC2 instances
    team: OPS2
    kind: ssh
    username: root
    ssh_key_data: ~/.ssh/id_rsa

    
  - name: Local SSH
    team: OPS2
    description:  Used for vagrant instances
    kind: ssh
    username: vagrant
    ssh_key_data: ~/.ssh/id_rsa


  - name: AWS creds2
    team: OPS
    description: Used for AWS 
    kind: aws
    username: YOU2
    password: CANTHANDLETHIS


  # - name: RAX creds
  #   description: Used for Rackspace 
  #   kind: rax
  #   username: me
  #   password: noyoucant


inventories:
  - name: Production2
    description: Production Machines
    groups:
      - name: EC2
        credential: AWS creds
        source: ec2
        description: EC2 hosts

  - name: Test
    description: Test Machines
    groups:
      - name: web
        source: manual
        hosts:
        - name: 10.42.0.6
        - name: 10.42.0.7
        - name: 10.42.0.8
        - name: 10.42.0.9
        - name: 10.42.0.10     
  - name: QA
    description: QA Machines

projects:
  - name: Example Playbooks
    description: Configures all the servers in Hyrule.
    scm_type: git
    scm_url: https://github.com/jsmartin/tower-demo-example-simple

  - name: Ansible Examples
    description: Some example roles and playbooks
    scm_type: git
    scm_url: https://github.com/ansible/ansible-examples

job_templates:
  - name: Apache2
    description: Confgure Apache servers
    inventory: Test
    project: Example Playbooks
    playbook: site.yml
    machine_credential: Local SSH
    job_type: run
    verbosity: 0
    forks: 5
